apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Release.Name }}-crole
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - list
- apiGroups:
  - ""
  resourceNames:
  - "{{ .Values.cluster.name }}-kubeconfig"
  resources:
  - secrets
  verbs:
  - get
