apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ .Release.Name }}-role
  namespace: {{ .Release.Namespace }}
rules:
- apiGroups:
  - argoproj.io
  resources:
  - appprojects
  - applications
  - applicationsets
  verbs:
  - get
  - list
- apiGroups:
  - ""
  resources:
  - configmaps
  - pods
  - secrets
  - services
  verbs:
  - get
  - list
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - delete
- apiGroups:
  - ""
  resources:
  - pods/portforward
  verbs:
  - create
  - get
  - list
  - watch
  - update
  - patch
  - delete
