apiVersion: infrastructure.cluster.x-k8s.io/v1beta2
kind: AWSManagedMachinePool
metadata:
  labels:
    {{- include "capieks.labels" . | nindent 4 }}
  name: {{ .Values.cluster.name }}-pool-0
spec:
  amiType: AL2023_x86_64_STANDARD
  roleName: nodes.cluster-api-provider-aws.sigs.k8s.io
  scaling:
    minSize: 1
    maxSize: 100
