apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  labels:
    {{- include "capieks.labels" . | nindent 4 }}
  name: {{ .Values.cluster.name }}
spec:
  clusterNetwork:
    pods:
      cidrBlocks:
      - {{ .Values.cluster.pod_network_cidr }}
  controlPlaneRef:
    apiVersion: controlplane.cluster.x-k8s.io/v1beta2
    kind: AWSManagedControlPlane
    name: {{ .Values.cluster.name }}-control-plane
  infrastructureRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1beta2
    kind: AWSManagedCluster
    name: {{ .Values.cluster.name }}
