apiVersion: cluster.x-k8s.io/v1beta1
kind: MachinePool
metadata:
  labels:
    {{- include "capieks.labels" . | nindent 4 }}
  name: {{ .Values.cluster.name }}-pool-0
spec:
  clusterName: {{ .Values.cluster.name }}
  replicas: {{ .Values.cluster.replicas }}
  template:
    spec:
      bootstrap:
        dataSecretName: ""
      clusterName: {{ .Values.cluster.name }}
      infrastructureRef:
        apiVersion: infrastructure.cluster.x-k8s.io/v1beta2
        kind: AWSManagedMachinePool
        name: {{ .Values.cluster.name }}-pool-0
